/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
module

public import InfinitaryLogic.Methods.LocalEMTruthLemma
public import InfinitaryLogic.Methods.EM.TailAdapter
public import InfinitaryLogic.Combinatorics.InfiniteRamseyFamily

/-!
# The local EM template-realization bridge

The adapter between the local EM truth-lemma stack (`LocalEMTruthLemma.lean`) and the honest
Morley–Hanf residual `MorleySeedTailTemplateRealizable` (`Conditional/MorleyHanfTransfer.lean`),
**parameterized by the restricted `OmegaCompleteForColim`** (the exact `ΓlocalColim`-restricted
completeness the truth lemma consumes — not the strictly stronger global `OmegaComplete`).
Four deliverables:

1. **`LocalStage.ofSeq`** — the seed stage of a formula sequence `s : ℕ → Σ n, L'.BoundedFormulaω
   Empty n`, with `Γ₀ = Set.range s`. Note the countability interface: `LocalStage` requires
   countably many function *and* relation symbols, while `TailTemplateRealizable` assumes only
   countable relations — the function-symbol countability is an explicit extra instance argument
   of this bridge for now (a later chunk can pass to the countable sublanguage generated by `s`).

2. **Subsequence-preserving extraction** (`exists_orderEmb_tailIndiscernible_ΓEMlocal`): from the
   *given* sequence `a : ℕ → M`, an order embedding `g : ℕ ↪o ℕ` with `a ∘ g` tail-indiscernible
   on `ΓEMlocal s₀`. No fresh `Infinite.natEmbedding M` (contrast `exists_ΓEMlocal_tail_indiscernible`,
   which extracts an unrelated sequence and so loses the input's template): the Ramsey colorings
   of `infinite_ramsey_nat_family` are pulled back along the input `a`, so no cardinality
   hypothesis on `M` is consumed. `exists_localEMContext_subseq` packages the result as a
   `LocalEMContext` with `ctx.a = a ∘ g` and `ctx.Γ = ΓEMlocal s₀`.

3. **Template preservation under subsequence**
   (`IsLomega1omegaIndiscernibleOnTail.tailTemplateOfSeq_comp_truth_iff`): for `⟨n, φ⟩ ∈ Γ` and
   `a` tail-indiscernible on `Γ`, the eventually-form template of `a ∘ g` agrees with that of `a`.
   The key adapter preventing the wrong template: the final residual is about the template of the
   *input* sequence `a`, while the truth lemma runs over the extracted `ctx.a = a ∘ g`.
   `templateTheoryOn_congr` transports the template theory across the agreement.

4. **The parameterized EM model theorem**: `realize_templateSentence_localEM_iff` — in the local
   EM term model, a template sentence over the seed language holds iff the eventually-form
   template of `ctx.a` declares its formula true (via `deFormClosedForColim_of_ΓEMlocal_subset`,
   `TLReadyStage_of_Γlocal`, `truthLemmaStage_of_mem`, and
   `realize_templateSentence_of_structure`) — and its packaging
   `LocalEMContext.templateTheoryOn_seed_model`: the quotient model satisfies every
   positive/negative sentence of the seed-family template theory.

**Acceptance** (`tailTemplateRealizable_of_localEM`): given a tail-indiscernible-on-`Set.range s`
input `a` and, **for that `s`**, an extracted subsequence context that is `OmegaCompleteForColim`,
the tail-template theory of `a` over any target order `J` has a model. This per-`s` lemma is
hypothesis-relative and true as stated — but its ∀-`s` closure is **false-shaped** (a seed
enumerating `{Pᵢ x}ᵢ ∪ {⋀ᵢ Pᵢ x}` against a height model has a finitely-satisfiable,
unsatisfiable tail-template theory; see `TailTemplateRealizable`'s docstring in
`Conditional/MorleyHanfTransfer.lean`), so no named residual quantifies over arbitrary `s`. The
named residuals are **seed-specific and source-aware**: `MorleySeedOmegaExtraction` (the
acceptance bundle at `s := morleySeed φ`, carrying `Sentenceω.Realize φ M`, the `ℶ_{ω₁}` size
premise, and pairwise distinctness) and its cleanest form `MorleySeedOmegaHomogeneousExtraction`
— the `J`-free source-side homogeneity residual (via
`omegaCompleteForColim_of_omegaHomogeneous` and
`morleySeedOmegaExtraction_of_homogeneousExtraction`): a countable-family homogeneity extraction
statement about `a ∘ g` on the seed family — no term model, no quotients, no supports.

This file imports the EM-side template machinery (`Methods/EM/TailAdapter.lean`), so it is NOT
part of the pure local stack guarded by `check_local_boundary.sh`'s EM-free roots; it must stay
**Conditional-free** (checked by the same script), leaving `TailTemplateRealizable` itself to a
downstream Conditional-touching file.
-/

@[expose] public section

universe u v

namespace FirstOrder.Language

/-! ## 1. The seed stage of a formula sequence -/

/-- The **seed stage of a formula sequence**: stage language `L'`, stage family `Set.range s`.
The countability certificates are instance arguments; note `TailTemplateRealizable` itself
assumes only countably many *relation* symbols, so the function-symbol countability is an extra
assumption of this bridge for now (a later chunk can replace `L'` by the countable sublanguage
generated by `s`). -/
@[reducible] def LocalStage.ofSeq (L' : Language.{0, 0}) [hf : Countable (Σ n, L'.Functions n)]
    [hr : Countable (Σ n, L'.Relations n)] (s : ℕ → Σ n, L'.BoundedFormulaω Empty n) :
    LocalStage where
  Lang := L'
  Gamma := Set.range s
  gamma_countable := Set.countable_range s
  fun_countable := hf
  rel_countable := hr

@[simp] theorem LocalStage.ofSeq_Lang (L' : Language.{0, 0})
    [Countable (Σ n, L'.Functions n)] [Countable (Σ n, L'.Relations n)]
    (s : ℕ → Σ n, L'.BoundedFormulaω Empty n) : (LocalStage.ofSeq L' s).Lang = L' := rfl

@[simp] theorem Γlocal_ofSeq_zero (L' : Language.{0, 0})
    [Countable (Σ n, L'.Functions n)] [Countable (Σ n, L'.Relations n)]
    (s : ℕ → Σ n, L'.BoundedFormulaω Empty n) :
    Γlocal (LocalStage.ofSeq L' s) 0 = Set.range s := rfl

/-! ## Skeleton-constant terms: support and deep interpretation -/

section ConstTerm

variable (Λ : Language.{0, 0}) (J : Type) [LinearOrder J]

/-- The skeleton support of a skeleton-constant term is the singleton of its index. -/
theorem locJSupport_constTerm (j : J) :
    locJSupport Λ J
      (Term.func (Sum.inr j : Λ[[J]].Functions 0) Fin.elim0 : Λ[[J]].Term Empty) = {j} := by
  show (Finset.univ.biUnion fun k : Fin 0 =>
        locJSupport Λ J ((Fin.elim0 : Fin 0 → Λ[[J]].Term Empty) k))
      ∪ locJConstOf Λ J (Sum.inr j : Λ[[J]].Functions 0) = {j}
  rw [Finset.univ_eq_empty, Finset.biUnion_empty, Finset.empty_union]
  rfl

variable {M : Type} [Λ.Structure M]

/-- The deep interpretation of a skeleton-constant term is the deep sequence at the constant's
rank position — the semantic content of "the `J`-skeleton is interpreted by the deep tuple".
Definitional: the sum/`constantsOn` `funMap` coherence reduces. -/
theorem locDeepInterp_constTerm (a : ℕ → M) (d : ℕ) (S : Finset J) (j : J) :
    locDeepInterp Λ J a d S
      (Term.func (Sum.inr j : Λ[[J]].Functions 0) Fin.elim0 : Λ[[J]].Term Empty)
      = a (d + deepRank J S j) := rfl

end ConstTerm

/-! ## 2. Subsequence-preserving extraction

The Ramsey colorings are pulled back along the **input** sequence `a`, so the extracted
tail-indiscernible sequence is a subsequence `a ∘ g` (preserving `a`'s template, per §3) and no
cardinality hypothesis on `M` is consumed — contrast `exists_ΓEMlocal_tail_indiscernible`, whose
`Infinite.natEmbedding` discards the input sequence. -/

/-- **Subsequence-preserving extraction**: some subsequence of the given `a` is
tail-indiscernible on the whole countable local family `ΓEMlocal s₀`. Infinite-Ramsey on the
formula-truth colorings of increasing `a`-tuples, via `infinite_ramsey_nat_family`. -/
theorem exists_orderEmb_tailIndiscernible_ΓEMlocal (s₀ : LocalStage) (M : Type)
    [s₀.Lang.Structure M] [Nonempty M] (a : ℕ → M) :
    letI : (localColim s₀).Structure M := localColimStructure s₀
    ∃ g : ℕ ↪o ℕ, IsLomega1omegaIndiscernibleOnTail (a ∘ ⇑g) (ΓEMlocal s₀) := by
  classical
  let : (localColim s₀).Structure M := localColimStructure s₀
  obtain ⟨e, he⟩ := exists_ΓEMlocalEnum s₀
  -- Pull each family formula's truth back to a `Bool` coloring of strictly-increasing
  -- tuples of the INPUT sequence `a`.
  let c : ℕ → Σ n, (Fin n ↪o ℕ) → Bool := fun i =>
    ⟨(e i).1, fun t => decide ((e i).2.Realize (Empty.elim : Empty → M) (fun k => a (t k)))⟩
  obtain ⟨g, hg⟩ := infinite_ramsey_nat_family c
  refine ⟨g, ?_⟩
  intro n φ hmem
  rw [he] at hmem
  obtain ⟨i, hi⟩ := hmem
  obtain ⟨N, hN⟩ := hg i
  refine ⟨N, ?_⟩
  intro u v hu hv hu_deep hv_deep
  -- Arity transport: `(c i).1 = n`.
  have hnEq : (c i).1 = n := by simp [c, hi]
  let uC : Fin (c i).1 ↪o ℕ := hnEq ▸ OrderEmbedding.ofStrictMono u hu
  let vC : Fin (c i).1 ↪o ℕ := hnEq ▸ OrderEmbedding.ofStrictMono v hv
  have huCdeep : ∀ k, N ≤ uC k := by intro k; simp only [uC]; cases hnEq; exact hu_deep k
  have hvCdeep : ∀ k, N ≤ vC k := by intro k; simp only [vC]; cases hnEq; exact hv_deep k
  have hbool : (c i).2 (uC.trans g) = (c i).2 (vC.trans g) := hN uC vC huCdeep hvCdeep
  -- Decode the `Bool` equation back to a truth equivalence for `φ`.
  cases hnEq
  simp only [c, uC, vC, RelEmbedding.trans_apply, OrderEmbedding.coe_ofStrictMono] at hbool
  have hi_eta : (⟨(e i).fst, (e i).snd⟩ : Σ n, (localColim s₀).BoundedFormulaω Empty n) =
      ⟨(c i).fst, φ⟩ := hi
  obtain ⟨_, h_snd⟩ := Sigma.mk.inj_iff.mp hi_eta
  rw [eq_of_heq h_snd] at hbool
  show φ.Realize (Empty.elim : Empty → M) ((a ∘ ⇑g) ∘ u) ↔
       φ.Realize (Empty.elim : Empty → M) ((a ∘ ⇑g) ∘ v)
  exact decide_eq_decide.mp hbool

/-- **The subsequence context**: the extraction packaged as an actual `LocalEMContext` with
`ctx.a = a ∘ g` and `ctx.Γ = ΓEMlocal s₀` (membership obligations from the `ΓEMlocal`
dischargers). This proves every conjunct of the acceptance theorem's `hOmega` bundle **except**
`ctx.OmegaCompleteForColim` — the one honest hole this file leaves open. -/
theorem exists_localEMContext_subseq (s₀ : LocalStage) (J : Type) [LinearOrder J] (M : Type)
    [s₀.Lang.Structure M] [Nonempty M] (a : ℕ → M) :
    letI : (localColim s₀).Structure M := localColimStructure s₀
    ∃ (g : ℕ ↪o ℕ) (ctx : LocalEMContext (localColim s₀) J (M := M)),
      ctx.a = a ∘ ⇑g ∧ ctx.Γ = ΓEMlocal s₀ := by
  let : (localColim s₀).Structure M := localColimStructure s₀
  obtain ⟨g, hind⟩ := exists_orderEmb_tailIndiscernible_ΓEMlocal s₀ M a
  exact ⟨g, ⟨a ∘ ⇑g, ΓEMlocal s₀, hind, locDeEqAtom_mem_ΓEMlocal J s₀,
    locDeRelAtom_mem_ΓEMlocal J s₀⟩, rfl, rfl⟩

/-! ## 3. Template preservation under subsequence -/

/-- **Template preservation under subsequence** (the key adapter preventing the wrong template):
for a family formula, the eventually-form template of a subsequence `a ∘ g` agrees with that of
`a`, provided `a` is tail-indiscernible on the family. Both directions route through `a`'s truth
collapse (`tailTemplateOfSeq_truth_iff`), using that `g`-images of deep tuples are deep
(`StrictMono.le_apply`). -/
theorem IsLomega1omegaIndiscernibleOnTail.tailTemplateOfSeq_comp_truth_iff
    {L : Language.{u, v}} {M : Type*} [L.Structure M] {a : ℕ → M}
    {Γ : Set (Σ n, L.BoundedFormulaω Empty n)}
    (h : IsLomega1omegaIndiscernibleOnTail (L := L) a Γ) (g : ℕ ↪o ℕ)
    {n : ℕ} {φ : L.BoundedFormulaω Empty n} (hφ : ⟨n, φ⟩ ∈ Γ) :
    (tailTemplateOfSeq (L := L) (a ∘ ⇑g)).truth φ ↔ (tailTemplateOfSeq (L := L) a).truth φ := by
  obtain ⟨N, hN⟩ := h.tailTemplateOfSeq_truth_iff hφ
  constructor
  · rintro ⟨N', hN'⟩
    obtain ⟨u, hu_mono, hu_deep⟩ := exists_strictMono_of_le n (max N N')
    have hgu_mono : StrictMono (⇑g ∘ u) := g.strictMono.comp hu_mono
    have hgu_deep : ∀ k, N ≤ (⇑g ∘ u) k := fun k =>
      le_trans (le_trans (le_max_left _ _) (hu_deep k)) g.strictMono.le_apply
    have hreal : φ.Realize (Empty.elim : Empty → M) (a ∘ (⇑g ∘ u)) := by
      have hu' := hN' u hu_mono fun k => le_trans (le_max_right _ _) (hu_deep k)
      simpa [Function.comp_assoc] using hu'
    exact (hN (⇑g ∘ u) hgu_mono hgu_deep).mpr hreal
  · intro htruth
    refine ⟨N, fun u hu_mono hu_deep => ?_⟩
    have hgu_mono : StrictMono (⇑g ∘ u) := g.strictMono.comp hu_mono
    have hgu_deep : ∀ k, N ≤ (⇑g ∘ u) k := fun k => le_trans (hu_deep k) g.strictMono.le_apply
    have hu' := (hN (⇑g ∘ u) hgu_mono hgu_deep).mp htruth
    simpa [Function.comp_assoc] using hu'

/-- Templates that agree on a family generate the same restricted template theory. Transports
`templateTheoryOn` (hence `templateTheoryOfSeq`) across the subsequence agreement of the previous
lemma. -/
theorem Lomega1omegaTemplate.templateTheoryOn_congr {L : Language.{u, v}}
    {T T' : Lomega1omegaTemplate L} {Γ : Set (Σ n, L.BoundedFormulaω Empty n)}
    (h : ∀ (n : ℕ) (φ : L.BoundedFormulaω Empty n), ⟨n, φ⟩ ∈ Γ → (T.truth φ ↔ T'.truth φ))
    (J : Type u) [LinearOrder J] :
    T.templateTheoryOn Γ J = T'.templateTheoryOn Γ J := by
  ext σ
  constructor
  · rintro ⟨n, φ, t, hΓφ, hcase⟩
    exact ⟨n, φ, t, hΓφ, hcase.imp (fun p => ⟨(h n φ hΓφ).mp p.1, p.2⟩)
      (fun p => ⟨fun hT' => p.1 ((h n φ hΓφ).mpr hT'), p.2⟩)⟩
  · rintro ⟨n, φ, t, hΓφ, hcase⟩
    exact ⟨n, φ, t, hΓφ, hcase.imp (fun p => ⟨(h n φ hΓφ).mpr p.1, p.2⟩)
      (fun p => ⟨fun hT => p.1 ((h n φ hΓφ).mp hT), p.2⟩)⟩

/-! ## 4. The parameterized EM model theorem -/

/-- **Seed restriction of tail indiscernibility**: a sequence tail-indiscernible (over the
colimit structure) on a family containing `ΓEMlocal s₀` is tail-indiscernible, over the seed
language, on the seed family `Γlocal s₀ 0` — via the colimit membership of seed images and the
semantic transport `realize_map_LlocalInclusion`. -/
theorem IsLomega1omegaIndiscernibleOnTail.seedOfΓEMlocal (s₀ : LocalStage) {M : Type}
    [s₀.Lang.Structure M] [Nonempty M] {a' : ℕ → M}
    {Γ : Set (Σ n, (localColim s₀).BoundedFormulaω Empty n)} (hΓ : ΓEMlocal s₀ ⊆ Γ)
    (h : letI : (localColim s₀).Structure M := localColimStructure s₀
      IsLomega1omegaIndiscernibleOnTail a' Γ) :
    IsLomega1omegaIndiscernibleOnTail (L := s₀.Lang) a' (Γlocal s₀ 0) := by
  let : (localColim s₀).Structure M := localColimStructure s₀
  intro n φ hφ
  obtain ⟨N, hN⟩ := h (hΓ (ΓlocalColim_subset_ΓEMlocal s₀
    (toLocalColimFormula_mem_ΓlocalColim s₀ (k := 0) hφ)))
  refine ⟨N, fun u v hu hv hud hvd => ?_⟩
  have hiff := hN u v hu hv hud hvd
  rwa [realize_map_LlocalInclusion, realize_map_LlocalInclusion] at hiff

/-- **Seed restriction of tail indiscernibility, generic core**: over ANY `localColim` structure,
the seed-language reduct transports tail indiscernibility on a family containing `ΓEMlocal s₀`
down to the seed family — the second canonical-structure dependency of the realization chain,
generalized. For the canonical structure this reduct is definitionally the original seed
structure. -/
theorem IsLomega1omegaIndiscernibleOnTail.seedOfΓEMlocal_of_reduct (s₀ : LocalStage) {M : Type}
    [(localColim s₀).Structure M] {a' : ℕ → M}
    {Γ : Set (Σ n, (localColim s₀).BoundedFormulaω Empty n)} (hΓ : ΓEMlocal s₀ ⊆ Γ)
    (h : IsLomega1omegaIndiscernibleOnTail (L := localColim s₀) a' Γ) :
    letI : (Llocal s₀ 0).Structure M := (LlocalInclusion s₀ 0).reduct M
    IsLomega1omegaIndiscernibleOnTail (L := Llocal s₀ 0) a' (Γlocal s₀ 0) := by
  let : (Llocal s₀ 0).Structure M := (LlocalInclusion s₀ 0).reduct M
  have : (LlocalInclusion s₀ 0).IsExpansionOn M := LHom.isExpansionOn_reduct _ _
  intro n φ hφ
  obtain ⟨N, hN⟩ := h (hΓ (ΓlocalColim_subset_ΓEMlocal s₀
    (toLocalColimFormula_mem_ΓlocalColim s₀ (k := 0) hφ)))
  refine ⟨N, fun u v hu hv hud hvd => ?_⟩
  have hiff := hN u v hu hv hud hvd
  exact ((BoundedFormulaω.realize_mapLanguage (LlocalInclusion s₀ 0) φ Empty.elim
      (a' ∘ u)).symm.trans
    (hiff.trans (BoundedFormulaω.realize_mapLanguage (LlocalInclusion s₀ 0) φ Empty.elim
      (a' ∘ v))))

/-- **The key realization equivalence, generic core**: over ANY `localColim` source structure
satisfying the Skolem-universality mixin, with the source's seed semantics read through the
seed-language reduct. Same chain as the canonical version below, fed by the generic staged truth
lemma and the generic seed restriction. -/
theorem realize_templateSentence_localEM_iff_of_skolemUniversal (s₀ : LocalStage) (J : Type)
    [LinearOrder J] {M : Type} [(localColim s₀).Structure M]
    (hsk : LocalSkolemUniversalForColim s₀ (M := M)) :
    letI : s₀.Lang.Structure M := (LlocalInclusion s₀ 0).reduct M
    ∀ (ctx : LocalEMContext (localColim s₀) J (M := M)),
      ΓEMlocal s₀ ⊆ ctx.Γ → LocalEMContext.OmegaCompleteForColim s₀ J ctx →
      ∀ {n : ℕ} (φ : s₀.Lang.BoundedFormulaω Empty n),
        (⟨n, φ⟩ : Σ n, s₀.Lang.BoundedFormulaω Empty n) ∈ Γlocal s₀ 0 →
        ∀ (t : Fin n ↪o J),
          letI : (localColim s₀)[[J]].Structure ctx.Carrier := ctx.structure
          letI : (s₀.Lang)[[J]].Structure ctx.Carrier :=
            ((LlocalInclusion s₀ 0).addConstants J).reduct ctx.Carrier
          (Sentenceω.Realize (Lomega1omegaTemplate.templateSentence φ t) ctx.Carrier ↔
            (tailTemplateOfSeq (L := s₀.Lang) ctx.a).truth φ) := by
  let : s₀.Lang.Structure M := (LlocalInclusion s₀ 0).reduct M
  let : (Llocal s₀ 0).Structure M := (inferInstance : s₀.Lang.Structure M)
  have : (LlocalInclusion s₀ 0).IsExpansionOn M := LHom.isExpansionOn_reduct _ _
  intro ctx hΓ hc n φ hmem t
  let : (localColim s₀)[[J]].Structure ctx.Carrier := ctx.structure
  let : (s₀.Lang)[[J]].Structure ctx.Carrier :=
    ((LlocalInclusion s₀ 0).addConstants J).reduct ctx.Carrier
  -- the closed skeleton-constant argument terms and their common support
  set ts : Fin n → (localColim s₀)[[J]].Term Empty :=
    fun i => Term.func (Sum.inr (t i) : (localColim s₀)[[J]].Functions 0) Fin.elim0 with hts
  set S : Finset J := Finset.univ.image (fun i => t i) with hSdef
  have htmem : ∀ i, t i ∈ S := by
    intro i; rw [hSdef]; exact Finset.mem_image_of_mem _ (Finset.mem_univ i)
  have hsub : ∀ i, locJSupport (localColim s₀) J (ts i) ⊆ S := by
    intro i
    rw [hts]
    rw [locJSupport_constTerm (localColim s₀) J (t i), Finset.singleton_subset_iff]
    exact htmem i
  -- the generic truth lemma at the seed stage
  have hclosed := LocalEMContext.deFormClosedForColim_of_ΓEMlocal_subset s₀ J ctx hΓ
  have hready := LocalEMContext.TLReadyStage_of_Γlocal s₀ J ctx (k := 0) hclosed φ hmem ts S hsub
  have hTL := LocalEMContext.truthLemmaStage_of_mem_of_skolemUniversal s₀ J hsk ctx hc 0 φ hmem
    ts S hsub hready
  refine Iff.trans ?_ (Iff.trans hTL ?_)
  · -- sentence realization ↔ carrier realization on the term classes
    have hbase := realize_templateSentence_of_structure (L := s₀.Lang) (J := J)
      (N := ctx.Carrier) φ t
    have hbt : (fun i => (Term.func (Sum.inr (t i) : (s₀.Lang)[[J]].Functions 0)
          Fin.elim0 : (s₀.Lang)[[J]].Term Empty).realize (Empty.elim : Empty → ctx.Carrier))
        = fun i => ctx.mkClass (t := ts i) := by
      funext i
      show @Structure.funMap ((localColim s₀)[[J]]) ctx.Carrier ctx.structure 0
          (Sum.inr (t i))
          (fun k => ((Fin.elim0 : Fin 0 → (s₀.Lang)[[J]].Term Empty) k).realize
            (Empty.elim : Empty → ctx.Carrier)) = _
      rw [show (fun k : Fin 0 => ((Fin.elim0 : Fin 0 → (s₀.Lang)[[J]].Term Empty) k).realize
          (Empty.elim : Empty → ctx.Carrier)) = (Fin.elim0 : Fin 0 → ctx.Carrier)
        from funext fun k => k.elim0]
      exact LocalEMContext.constMap_mkClass (Λ := localColim s₀) (J := J) ctx (Sum.inr (t i))
    rw [hbt] at hbase
    -- peel the two language maps off the truth-lemma side
    let : (localColim s₀).Structure ctx.Carrier := ctx.structureBase
    have : (lhomWithConstants (localColim s₀) J).IsExpansionOn ctx.Carrier :=
      ctx.lhomWithConstants_isExpansionOn
    let : (Llocal s₀ 0).Structure ctx.Carrier := (LlocalInclusion s₀ 0).reduct ctx.Carrier
    exact hbase.trans
      ((BoundedFormulaω.realize_mapLanguage (lhomWithConstants (localColim s₀) J)
          (φ.mapLanguage (LlocalInclusion s₀ 0)) Empty.elim
          (fun i => ctx.mkClass (t := ts i))).trans
        (BoundedFormulaω.realize_mapLanguage (LlocalInclusion s₀ 0) φ Empty.elim
          (fun i => ctx.mkClass (t := ts i)))).symm
  · -- eventual deep truth ↔ tail-template truth of `ctx.a`
    have hTail0 : IsLomega1omegaIndiscernibleOnTail (L := s₀.Lang) ctx.a (Γlocal s₀ 0) :=
      IsLomega1omegaIndiscernibleOnTail.seedOfΓEMlocal_of_reduct s₀ hΓ ctx.hind
    obtain ⟨N, hN⟩ := hTail0.tailTemplateOfSeq_truth_iff hmem
    have htmono : ∀ d : ℕ, StrictMono fun i : Fin n => d + deepRank J S (t i) := by
      intro d i i' hii'
      exact Nat.add_lt_add_left
        (deepRank_lt_of_lt (J := J) (htmem i) (t.strictMono hii')) d
    have hED : LocalEMContext.eventualDeepTruth (Λ := localColim s₀) (J := J) ctx
        (φ.mapLanguage (LlocalInclusion s₀ 0)) ts S ↔
        ∀ᶠ d in Filter.atTop, φ.Realize (Empty.elim : Empty → M)
          (ctx.a ∘ fun i => d + deepRank J S (t i)) := by
      rw [LocalEMContext.eventualDeepTruth]
      refine Filter.eventually_congr (Filter.Eventually.of_forall fun d => ?_)
      have hassign : (fun i => locDeepInterp (localColim s₀) J ctx.a d S (ts i))
          = ctx.a ∘ fun i => d + deepRank J S (t i) := by
        funext i
        rw [hts]
        exact locDeepInterp_constTerm (localColim s₀) J ctx.a d S (t i)
      rw [hassign]
      exact BoundedFormulaω.realize_mapLanguage (LlocalInclusion s₀ 0) φ
        (Empty.elim : Empty → M) (ctx.a ∘ fun i => d + deepRank J S (t i))
    rw [hED]
    constructor
    · intro hev
      rw [Filter.eventually_atTop] at hev
      obtain ⟨d₀, hd₀⟩ := hev
      exact (hN (fun i => max N d₀ + deepRank J S (t i)) (htmono _)
        (fun k => le_trans (le_max_left _ _) (Nat.le_add_right _ _))).mpr
        (hd₀ (max N d₀) (le_max_right _ _))
    · intro htruth
      rw [Filter.eventually_atTop]
      exact ⟨N, fun d hd => (hN (fun i => d + deepRank J S (t i)) (htmono d)
        (fun k => le_trans hd (Nat.le_add_right _ _))).mp htruth⟩

/-- **The parameterized EM model theorem, generic core**: the quotient model satisfies the seed
template theory of `ctx.a`, over any mixin-satisfying source with seed semantics through the
reduct. -/
theorem LocalEMContext.templateTheoryOn_seed_model_of_skolemUniversal (s₀ : LocalStage) (J : Type)
    [LinearOrder J] {M : Type} [(localColim s₀).Structure M]
    (hsk : LocalSkolemUniversalForColim s₀ (M := M)) :
    letI : s₀.Lang.Structure M := (LlocalInclusion s₀ 0).reduct M
    ∀ (ctx : LocalEMContext (localColim s₀) J (M := M)),
      ΓEMlocal s₀ ⊆ ctx.Γ → LocalEMContext.OmegaCompleteForColim s₀ J ctx →
      letI : (localColim s₀)[[J]].Structure ctx.Carrier := ctx.structure
      letI : (s₀.Lang)[[J]].Structure ctx.Carrier :=
        ((LlocalInclusion s₀ 0).addConstants J).reduct ctx.Carrier
      Theoryω.Model
        ((tailTemplateOfSeq (L := s₀.Lang) ctx.a).templateTheoryOn (Γlocal s₀ 0) J)
        ctx.Carrier := by
  let : s₀.Lang.Structure M := (LlocalInclusion s₀ 0).reduct M
  intro ctx hΓ hc
  let : (localColim s₀)[[J]].Structure ctx.Carrier := ctx.structure
  let : (s₀.Lang)[[J]].Structure ctx.Carrier :=
    ((LlocalInclusion s₀ 0).addConstants J).reduct ctx.Carrier
  rintro τ ⟨n, φ, t, hmem, hcase⟩
  have hkey := realize_templateSentence_localEM_iff_of_skolemUniversal s₀ J hsk ctx hΓ hc
    φ hmem t
  rcases hcase with ⟨htruth, rfl⟩ | ⟨htruth, rfl⟩
  · exact hkey.mpr htruth
  · show BoundedFormulaω.Realize
      ((Lomega1omegaTemplate.templateSentence φ t).not : (s₀.Lang)[[J]].Sentenceω)
      (Empty.elim : Empty → ctx.Carrier) Fin.elim0
    rw [BoundedFormulaω.realize_not]
    exact fun hreal => htruth (hkey.mp hreal)

/-- **The key realization equivalence**: in the local EM term model (over any context with
`ΓEMlocal`-closure and `OmegaComplete`), a template sentence over the seed language holds iff
the eventually-form template of `ctx.a` declares its formula true. The chain: constant terms
realize as their term classes (`constMap_mkClass`); the language maps peel off
(`realize_templateSentence_of_structure` + `realize_mapLanguage` twice); the staged truth lemma
(`truthLemmaStage_of_mem`, fed by `TLReadyStage_of_Γlocal` and the discharged deForm mixin)
converts to eventual deep truth; the deep interpretation of the `J`-skeleton is a deep tuple of
`ctx.a` (`locDeepInterp_constTerm`), so the truth collapse of tail indiscernibility finishes. -/
theorem realize_templateSentence_localEM_iff (s₀ : LocalStage) (J : Type) [LinearOrder J]
    {M : Type} [s₀.Lang.Structure M] [Nonempty M] :
    letI : (localColim s₀).Structure M := localColimStructure s₀
    ∀ (ctx : LocalEMContext (localColim s₀) J (M := M)),
      ΓEMlocal s₀ ⊆ ctx.Γ → LocalEMContext.OmegaCompleteForColim s₀ J ctx →
      ∀ {n : ℕ} (φ : s₀.Lang.BoundedFormulaω Empty n),
        (⟨n, φ⟩ : Σ n, s₀.Lang.BoundedFormulaω Empty n) ∈ Γlocal s₀ 0 →
        ∀ (t : Fin n ↪o J),
          letI : (localColim s₀)[[J]].Structure ctx.Carrier := ctx.structure
          letI : (s₀.Lang)[[J]].Structure ctx.Carrier :=
            ((LlocalInclusion s₀ 0).addConstants J).reduct ctx.Carrier
          (Sentenceω.Realize (Lomega1omegaTemplate.templateSentence φ t) ctx.Carrier ↔
            (tailTemplateOfSeq (L := s₀.Lang) ctx.a).truth φ) := by
  let : (localColim s₀).Structure M := localColimStructure s₀
  intro ctx hΓ hc n φ hmem t
  let : (localColim s₀)[[J]].Structure ctx.Carrier := ctx.structure
  let : (s₀.Lang)[[J]].Structure ctx.Carrier :=
    ((LlocalInclusion s₀ 0).addConstants J).reduct ctx.Carrier
  -- the closed skeleton-constant argument terms and their common support
  set ts : Fin n → (localColim s₀)[[J]].Term Empty :=
    fun i => Term.func (Sum.inr (t i) : (localColim s₀)[[J]].Functions 0) Fin.elim0 with hts
  set S : Finset J := Finset.univ.image (fun i => t i) with hSdef
  have htmem : ∀ i, t i ∈ S := by
    intro i; rw [hSdef]; exact Finset.mem_image_of_mem _ (Finset.mem_univ i)
  have hsub : ∀ i, locJSupport (localColim s₀) J (ts i) ⊆ S := by
    intro i
    rw [hts]
    rw [locJSupport_constTerm (localColim s₀) J (t i), Finset.singleton_subset_iff]
    exact htmem i
  -- the truth lemma at the seed stage
  have hclosed := LocalEMContext.deFormClosedForColim_of_ΓEMlocal_subset s₀ J ctx hΓ
  have hready := LocalEMContext.TLReadyStage_of_Γlocal s₀ J ctx (k := 0) hclosed φ hmem ts S hsub
  have hTL := LocalEMContext.truthLemmaStage_of_mem s₀ J ctx hc 0 φ hmem ts S hsub hready
  refine Iff.trans ?_ (Iff.trans hTL ?_)
  · -- sentence realization ↔ carrier realization on the term classes
    have hbase := realize_templateSentence_of_structure (L := s₀.Lang) (J := J)
      (N := ctx.Carrier) φ t
    have hbt : (fun i => (Term.func (Sum.inr (t i) : (s₀.Lang)[[J]].Functions 0)
          Fin.elim0 : (s₀.Lang)[[J]].Term Empty).realize (Empty.elim : Empty → ctx.Carrier))
        = fun i => ctx.mkClass (t := ts i) := by
      funext i
      show @Structure.funMap ((localColim s₀)[[J]]) ctx.Carrier ctx.structure 0
          (Sum.inr (t i))
          (fun k => ((Fin.elim0 : Fin 0 → (s₀.Lang)[[J]].Term Empty) k).realize
            (Empty.elim : Empty → ctx.Carrier)) = _
      rw [show (fun k : Fin 0 => ((Fin.elim0 : Fin 0 → (s₀.Lang)[[J]].Term Empty) k).realize
          (Empty.elim : Empty → ctx.Carrier)) = (Fin.elim0 : Fin 0 → ctx.Carrier)
        from funext fun k => k.elim0]
      exact LocalEMContext.constMap_mkClass (Λ := localColim s₀) (J := J) ctx (Sum.inr (t i))
    rw [hbt] at hbase
    -- peel the two language maps off the truth-lemma side
    let : (localColim s₀).Structure ctx.Carrier := ctx.structureBase
    have : (lhomWithConstants (localColim s₀) J).IsExpansionOn ctx.Carrier :=
      ctx.lhomWithConstants_isExpansionOn
    let : (Llocal s₀ 0).Structure ctx.Carrier := (LlocalInclusion s₀ 0).reduct ctx.Carrier
    exact hbase.trans
      ((BoundedFormulaω.realize_mapLanguage (lhomWithConstants (localColim s₀) J)
          (φ.mapLanguage (LlocalInclusion s₀ 0)) Empty.elim
          (fun i => ctx.mkClass (t := ts i))).trans
        (BoundedFormulaω.realize_mapLanguage (LlocalInclusion s₀ 0) φ Empty.elim
          (fun i => ctx.mkClass (t := ts i)))).symm
  · -- eventual deep truth ↔ tail-template truth of `ctx.a`
    have hTail0 : IsLomega1omegaIndiscernibleOnTail (L := s₀.Lang) ctx.a (Γlocal s₀ 0) :=
      IsLomega1omegaIndiscernibleOnTail.seedOfΓEMlocal s₀ hΓ ctx.hind
    obtain ⟨N, hN⟩ := hTail0.tailTemplateOfSeq_truth_iff hmem
    have htmono : ∀ d : ℕ, StrictMono fun i : Fin n => d + deepRank J S (t i) := by
      intro d i i' hii'
      exact Nat.add_lt_add_left
        (deepRank_lt_of_lt (J := J) (htmem i) (t.strictMono hii')) d
    have hED : LocalEMContext.eventualDeepTruth (Λ := localColim s₀) (J := J) ctx
        (φ.mapLanguage (LlocalInclusion s₀ 0)) ts S ↔
        ∀ᶠ d in Filter.atTop, φ.Realize (Empty.elim : Empty → M)
          (ctx.a ∘ fun i => d + deepRank J S (t i)) := by
      rw [LocalEMContext.eventualDeepTruth]
      refine Filter.eventually_congr (Filter.Eventually.of_forall fun d => ?_)
      have hassign : (fun i => locDeepInterp (localColim s₀) J ctx.a d S (ts i))
          = ctx.a ∘ fun i => d + deepRank J S (t i) := by
        funext i
        rw [hts]
        exact locDeepInterp_constTerm (localColim s₀) J ctx.a d S (t i)
      rw [hassign]
      exact realize_map_LlocalInclusion s₀ 0 φ (Empty.elim : Empty → M)
        (ctx.a ∘ fun i => d + deepRank J S (t i))
    rw [hED]
    constructor
    · intro hev
      rw [Filter.eventually_atTop] at hev
      obtain ⟨d₀, hd₀⟩ := hev
      exact (hN (fun i => max N d₀ + deepRank J S (t i)) (htmono _)
        (fun k => le_trans (le_max_left _ _) (Nat.le_add_right _ _))).mpr
        (hd₀ (max N d₀) (le_max_right _ _))
    · intro htruth
      rw [Filter.eventually_atTop]
      exact ⟨N, fun d hd => (hN (fun i => d + deepRank J S (t i)) (htmono d)
        (fun k => le_trans hd (Nat.le_add_right _ _))).mp htruth⟩

/-- **The parameterized EM model theorem**: the local EM quotient model satisfies every
positive/negative sentence of the seed-family template theory of `ctx.a` — for any context with
`ΓEMlocal`-closure, assuming `OmegaComplete`. Positive sentences by the key equivalence;
negative ones by its contrapositive. -/
theorem LocalEMContext.templateTheoryOn_seed_model (s₀ : LocalStage) (J : Type) [LinearOrder J]
    {M : Type} [s₀.Lang.Structure M] [Nonempty M] :
    letI : (localColim s₀).Structure M := localColimStructure s₀
    ∀ (ctx : LocalEMContext (localColim s₀) J (M := M)),
      ΓEMlocal s₀ ⊆ ctx.Γ → LocalEMContext.OmegaCompleteForColim s₀ J ctx →
      letI : (localColim s₀)[[J]].Structure ctx.Carrier := ctx.structure
      letI : (s₀.Lang)[[J]].Structure ctx.Carrier :=
        ((LlocalInclusion s₀ 0).addConstants J).reduct ctx.Carrier
      Theoryω.Model
        ((tailTemplateOfSeq (L := s₀.Lang) ctx.a).templateTheoryOn (Γlocal s₀ 0) J)
        ctx.Carrier := by
  let : (localColim s₀).Structure M := localColimStructure s₀
  intro ctx hΓ hc
  let : (localColim s₀)[[J]].Structure ctx.Carrier := ctx.structure
  let : (s₀.Lang)[[J]].Structure ctx.Carrier :=
    ((LlocalInclusion s₀ 0).addConstants J).reduct ctx.Carrier
  rintro τ ⟨n, φ, t, hmem, hcase⟩
  have hkey := realize_templateSentence_localEM_iff s₀ J ctx hΓ hc φ hmem t
  rcases hcase with ⟨htruth, rfl⟩ | ⟨htruth, rfl⟩
  · exact hkey.mpr htruth
  · show BoundedFormulaω.Realize
      ((Lomega1omegaTemplate.templateSentence φ t).not : (s₀.Lang)[[J]].Sentenceω)
      (Empty.elim : Empty → ctx.Carrier) Fin.elim0
    rw [BoundedFormulaω.realize_not]
    exact fun hreal => htruth (hkey.mp hreal)

/-! ## Full indiscernibility restores Ω-completeness

The refuted Ω-residuals all fail on *drift*: a tail-indiscernible sequence lets the truth value
of a de-substituted component at the depth-`d` consecutive tuple vary with `d` below its cutoff,
so the witnessing component of a countable connective can escape to infinity. Under **full**
(cutoff-`0`) restricted indiscernibility — `IsLomega1omegaIndiscernibleOn`, the classical
Erdős–Rado extraction output, whose production genuinely consumes the `ℶ_{ω₁}` premise (e.g. in
the height model it must move off the growing diagonal into a single large height fiber) — every
de-substituted formula in the family has ONE value on all strictly monotone tuples, so witnesses
cannot drift and the Ω-clauses hold outright. -/

/-- **Full indiscernibility restores the (refuted-for-tail) Ω-completeness**: if the context's
sequence is fully indiscernible on its family and the family contains the de-substituted
*components* of the `Γ'` disjunctions/conjunctions, then the support-covered Ω-clauses hold —
each component's eventual deep truth is a `d`-independent value, so a witness at one depth is a
witness at every depth. This is the reduction that replaces the false tail-side residuals; its
intended supply was the classical full-indiscernibility extraction
(`MorleyHanfExtraction`-shaped), not any `atTop` cutoff exchange — but that extraction was
itself found false-shaped (statement audit 2026-07-07; see its docstring), so the supply must
come from a fully indiscernible sequence in a *constructed* model (the template /
consistency-property route), where this reduction applies unchanged. -/
theorem LocalEMContext.omegaCompleteOn_of_indiscernibleOn
    {Λ : Language.{0, 0}} (J : Type) [LinearOrder J] {M : Type} [Λ.Structure M]
    (ctx : LocalEMContext Λ J (M := M))
    (hfull : IsLomega1omegaIndiscernibleOn (L := Λ) ctx.a ctx.Γ)
    {Γ' : Set (Σ n, Λ.BoundedFormulaω Empty n)}
    (hSup : ∀ {m : ℕ} (φs : ℕ → Λ.BoundedFormulaω Empty m),
      (⟨m, BoundedFormulaω.iSup φs⟩ : Σ n, Λ.BoundedFormulaω Empty n) ∈ Γ' →
      ∀ (i : ℕ) (ts : Fin m → Λ[[J]].Term Empty) (S : Finset J)
        (hcov : ∀ i, locJSupport Λ J (ts i) ⊆ S),
        (⟨S.card, locDeForm Λ J S (φs i) ts hcov⟩ : Σ n, Λ.BoundedFormulaω Empty n) ∈ ctx.Γ)
    (hInf : ∀ {m : ℕ} (φs : ℕ → Λ.BoundedFormulaω Empty m),
      (⟨m, BoundedFormulaω.iInf φs⟩ : Σ n, Λ.BoundedFormulaω Empty n) ∈ Γ' →
      ∀ (i : ℕ) (ts : Fin m → Λ[[J]].Term Empty) (S : Finset J)
        (hcov : ∀ i, locJSupport Λ J (ts i) ⊆ S),
        (⟨S.card, locDeForm Λ J S (φs i) ts hcov⟩ : Σ n, Λ.BoundedFormulaω Empty n) ∈ ctx.Γ) :
    LocalEMContext.OmegaCompleteOn (Λ := Λ) (J := J) ctx Γ' := by
  have hmono : ∀ (p d : ℕ), StrictMono fun k : Fin p => d + (k : ℕ) :=
    fun _ d _ _ hkk' => Nat.add_lt_add_left hkk' d
  constructor
  · intro m φs hmem ts S hcov hev
    rw [LocalEMContext.eventualDeepTruth] at hev
    obtain ⟨d₀, hd₀⟩ := hev.exists
    rw [BoundedFormulaω.realize_iSup] at hd₀
    obtain ⟨i, hi⟩ := hd₀
    refine ⟨i, ?_⟩
    rw [LocalEMContext.eventualDeepTruth]
    refine Filter.Eventually.of_forall fun d => ?_
    rw [← realize_locDeForm Λ J ctx.a d S (φs i) ts hcov]
    exact (hfull (hSup φs hmem i ts S hcov) (fun k => d + (k : ℕ)) (fun k => d₀ + (k : ℕ))
      (hmono _ d) (hmono _ d₀)).mpr
      ((realize_locDeForm Λ J ctx.a d₀ S (φs i) ts hcov).mpr hi)
  · intro m φs hmem ts S hcov hev
    rw [LocalEMContext.eventualDeepTruth]
    refine Filter.Eventually.of_forall fun d => ?_
    rw [BoundedFormulaω.realize_iInf]
    intro i
    have hi := hev i
    rw [LocalEMContext.eventualDeepTruth] at hi
    obtain ⟨dᵢ, hdᵢ⟩ := hi.exists
    rw [← realize_locDeForm Λ J ctx.a d S (φs i) ts hcov]
    exact (hfull (hInf φs hmem i ts S hcov) (fun k => d + (k : ℕ)) (fun k => dᵢ + (k : ℕ))
      (hmono _ d) (hmono _ dᵢ)).mpr
      ((realize_locDeForm Λ J ctx.a dᵢ S (φs i) ts hcov).mpr hdᵢ)

/-- **The colimit-family Ω-completeness from full indiscernibility, discharged**: for a context
whose family contains `ΓEMlocal` and whose sequence is fully indiscernible on it, the
support-covered `OmegaCompleteForColim` holds outright — the component memberships come from the
constructor-inversion plumbing (`iSup/iInf_component_mem_ΓlocalColim`) composed with the deForm
discharger (`locDeForm_mem_ΓEMlocal`). This replaces the (refuted) tail-side residuals as the
route into the truth lemma: what remains is producing the fully indiscernible sequence. The
in-`M` form (`MorleyHanfExtraction`) was found false-shaped (statement audit 2026-07-07; see
its docstring), so the sequence must come from a constructed model via the template /
consistency-property route; this discharger applies there unchanged. -/
theorem LocalEMContext.omegaCompleteForColim_of_indiscernibleOn (s₀ : LocalStage) (J : Type)
    [LinearOrder J] {M : Type} [(localColim s₀).Structure M]
    (ctx : LocalEMContext (localColim s₀) J (M := M)) (hΓ : ΓEMlocal s₀ ⊆ ctx.Γ)
    (hfull : IsLomega1omegaIndiscernibleOn (L := localColim s₀) ctx.a ctx.Γ) :
    LocalEMContext.OmegaCompleteForColim s₀ J ctx :=
  LocalEMContext.omegaCompleteOn_of_indiscernibleOn J ctx hfull
    (fun _ hmem i ts S hcov => hΓ (locDeForm_mem_ΓEMlocal J s₀ S
      (iSup_component_mem_ΓlocalColim s₀ hmem i) ts hcov))
    (fun _ hmem i ts S hcov => hΓ (locDeForm_mem_ΓEMlocal J s₀ S
      (iInf_component_mem_ΓlocalColim s₀ hmem i) ts hcov))

/-! ## Absolute template truths on the Morley seed

The Morley seed's two members have sequence-independent template values: a sentence's tail
template is its absolute truth in the model, and the disequality's is `True` for any pairwise
distinct sequence. So the templates of ANY two pairwise-distinct sequences agree on the seed —
which frees the realizing context's sequence from being a subsequence of the input. -/

/-- The tail template of any sequence assigns a **sentence** its absolute truth value (arity-`0`
formulas ignore the tuple). -/
theorem tailTemplateOfSeq_truth_sentence_iff {L : Language.{u, v}} {M : Type*} [L.Structure M]
    (c : ℕ → M) (φ : L.Sentenceω) :
    (tailTemplateOfSeq (L := L) c).truth φ ↔ Sentenceω.Realize φ M := by
  constructor
  · rintro ⟨N, hN⟩
    have h := hN Fin.elim0 (fun p _ _ => p.elim0) (fun p => p.elim0)
    rwa [show (c ∘ Fin.elim0 : Fin 0 → M) = Fin.elim0 from funext fun p => p.elim0] at h
  · intro h
    refine ⟨0, fun u _ _ => ?_⟩
    rw [show (c ∘ u : Fin 0 → M) = Fin.elim0 from funext fun p => p.elim0]
    exact h

/-- **Stage-0 sentence satisfaction transfers to the carrier** — the consumer-shaped bridge for
the small-model assembly (issue #11 unit 7a): a stage-0 sentence of `Γlocal s₀ 0` true in the
source is true in the seed-language reduct of the context's carrier. Arity zero of the
realization equivalence: `tailTemplateOfSeq_truth_sentence_iff` turns source truth into
template truth, `realize_templateSentence_localEM_iff_of_skolemUniversal` transfers it to the
carrier, and `realize_templateSentence_of_structure` removes the vacuous skeleton constants. -/
theorem LocalEMContext.realizes_stage0_sentence_of_skolemUniversal (s₀ : LocalStage)
    (J : Type) [LinearOrder J] {M : Type} [(localColim s₀).Structure M]
    (hsk : LocalSkolemUniversalForColim s₀ (M := M))
    (ctx : LocalEMContext (localColim s₀) J (M := M))
    (hΓ : ΓEMlocal s₀ ⊆ ctx.Γ) (hc : LocalEMContext.OmegaCompleteForColim s₀ J ctx)
    (φ : s₀.Lang.Sentenceω)
    (hmem : (⟨0, φ⟩ : Σ n, s₀.Lang.BoundedFormulaω Empty n) ∈ Γlocal s₀ 0)
    (hφ : (letI : s₀.Lang.Structure M := (LlocalInclusion s₀ 0).reduct M
      Sentenceω.Realize φ M)) :
    letI : (localColim s₀)[[J]].Structure ctx.Carrier := ctx.structure
    letI : (s₀.Lang)[[J]].Structure ctx.Carrier :=
      ((LlocalInclusion s₀ 0).addConstants J).reduct ctx.Carrier
    letI : s₀.Lang.Structure ctx.Carrier :=
      (s₀.Lang.lhomWithConstants J).reduct ctx.Carrier
    Sentenceω.Realize φ ctx.Carrier := by
  let : s₀.Lang.Structure M := (LlocalInclusion s₀ 0).reduct M
  let : (localColim s₀)[[J]].Structure ctx.Carrier := ctx.structure
  let : (s₀.Lang)[[J]].Structure ctx.Carrier :=
    ((LlocalInclusion s₀ 0).addConstants J).reduct ctx.Carrier
  let : s₀.Lang.Structure ctx.Carrier :=
    (s₀.Lang.lhomWithConstants J).reduct ctx.Carrier
  let t0 : Fin 0 ↪o J := ⟨⟨Fin.elim0, fun a => a.elim0⟩, fun {a} => a.elim0⟩
  have hiff := realize_templateSentence_localEM_iff_of_skolemUniversal s₀ J hsk ctx hΓ hc
    φ hmem t0
  have htruth : (tailTemplateOfSeq (L := s₀.Lang) ctx.a).truth φ :=
    (tailTemplateOfSeq_truth_sentence_iff ctx.a φ).mpr hφ
  have hbase := (realize_templateSentence_of_structure (L := s₀.Lang) (J := J)
    (N := ctx.Carrier) φ t0).mp (hiff.mpr htruth)
  rwa [show (fun i : Fin 0 => (Term.func (Sum.inr (t0 i) : (s₀.Lang)[[J]].Functions 0)
      Fin.elim0 : (s₀.Lang)[[J]].Term Empty).realize (Empty.elim : Empty → ctx.Carrier))
      = (Fin.elim0 : Fin 0 → ctx.Carrier) from funext fun i => i.elim0] at hbase

/-- The tail template of any **pairwise distinct** sequence declares the disequality true. -/
theorem tailTemplateOfSeq_truth_disEq {L : Language.{u, v}} {M : Type*} [L.Structure M]
    {c : ℕ → M} (hc : ∀ i j : ℕ, i ≠ j → c i ≠ c j) :
    (tailTemplateOfSeq (L := L) c).truth (disEqFormula : L.BoundedFormulaω Empty 2) := by
  refine ⟨0, fun u hu _ => ?_⟩
  simp only [disEqFormula, BoundedFormulaω.realize_not, BoundedFormulaω.realize_equal,
    Term.realize_var]
  intro heq
  exact hc (u 0) (u 1) (ne_of_lt (hu (show (0 : Fin 2) < 1 by decide))) heq

/-- **Morley-seed template agreement**: the tail templates of any two pairwise-distinct sequences
in the same model agree on `Set.range (morleySeed φ)` — the sentence member's value is absolute,
and the disequality member's is `True` for both. -/
theorem morleySeed_template_agreement {L' : Language.{0, 0}} {M : Type} [L'.Structure M]
    (φ : L'.Sentenceω) {a b : ℕ → M}
    (ha : ∀ i j : ℕ, i ≠ j → a i ≠ a j) (hb : ∀ i j : ℕ, i ≠ j → b i ≠ b j) :
    ∀ (n : ℕ) (ψ : L'.BoundedFormulaω Empty n), ⟨n, ψ⟩ ∈ Set.range (morleySeed φ) →
      ((tailTemplateOfSeq (L := L') b).truth ψ ↔ (tailTemplateOfSeq (L := L') a).truth ψ) := by
  rintro n ψ ⟨k, hk⟩
  match k, hk with
  | 0, hk =>
    cases hk
    rw [tailTemplateOfSeq_truth_sentence_iff, tailTemplateOfSeq_truth_sentence_iff]
  | 1, hk =>
    cases hk
    exact iff_of_true (tailTemplateOfSeq_truth_disEq hb) (tailTemplateOfSeq_truth_disEq ha)
  | k + 2, hk =>
    cases hk
    rw [tailTemplateOfSeq_truth_sentence_iff, tailTemplateOfSeq_truth_sentence_iff]

/-- **Cross-model Morley-seed template agreement**: the seed construction does not require the two
sequences to live in the same model — the tail templates of pairwise-distinct sequences in any two
models both realizing the seed sentence agree on `Set.range (morleySeed φ)`. This is the form the
schema term model consumes (its sequence lives in the constructed quotient, not in the source). -/
theorem morleySeed_template_agreement_cross {L' : Language.{0, 0}} {M N : Type}
    [L'.Structure M] [L'.Structure N]
    (φ : L'.Sentenceω) {a : ℕ → M} {b : ℕ → N}
    (hφM : Sentenceω.Realize φ M) (hφN : Sentenceω.Realize φ N)
    (ha : ∀ i j : ℕ, i ≠ j → a i ≠ a j) (hb : ∀ i j : ℕ, i ≠ j → b i ≠ b j) :
    ∀ (n : ℕ) (ψ : L'.BoundedFormulaω Empty n), ⟨n, ψ⟩ ∈ Set.range (morleySeed φ) →
      ((tailTemplateOfSeq (L := L') b).truth ψ ↔ (tailTemplateOfSeq (L := L') a).truth ψ) := by
  rintro n ψ ⟨k, hk⟩
  match k, hk with
  | 0, hk =>
    cases hk
    rw [tailTemplateOfSeq_truth_sentence_iff, tailTemplateOfSeq_truth_sentence_iff]
    exact iff_of_true hφN hφM
  | 1, hk =>
    cases hk
    exact iff_of_true (tailTemplateOfSeq_truth_disEq hb) (tailTemplateOfSeq_truth_disEq ha)
  | k + 2, hk =>
    cases hk
    rw [tailTemplateOfSeq_truth_sentence_iff, tailTemplateOfSeq_truth_sentence_iff]
    exact iff_of_true hφN hφM

/-- **The `IsEmpty J` degenerate case**: over an empty target order, the Morley-seed template
theory contains only the arity-`0` (sentence) members, and the source model `M` itself realizes
them — no EM construction needed. -/
theorem morleySeed_theory_model_of_isEmptyJ {L' : Language.{0, 0}} {M : Type}
    [L'.Structure M] (φ : L'.Sentenceω) (a : ℕ → M) (J : Type) [LinearOrder J]
    [IsEmpty J] (hφreal : Sentenceω.Realize φ M) :
    ∃ (N : Type) (_ : L'[[J]].Structure N),
      Theoryω.Model
        ((tailTemplateOfSeq (L := L') a).templateTheoryOfSeq (morleySeed φ) J) N := by
  let : (constantsOn J).Structure M := constantsOn.structure fun j => isEmptyElim j
  refine ⟨M, inferInstance, ?_⟩
  rintro σ ⟨n, ψ, t, ⟨k, hk⟩, hcase⟩
  match k, hk with
  | 1, hk =>
    cases hk
    exact isEmptyElim (t 0)
  | 0, hk =>
    cases hk
    rcases hcase with ⟨_, rfl⟩ | ⟨hnot, _⟩
    · refine (realize_templateSentence_of_structure (L := L') (J := J) (N := M) φ t).mpr ?_
      rw [show (fun i : Fin 0 => (Term.func (Sum.inr (t i) : L'[[J]].Functions 0)
          Fin.elim0 : L'[[J]].Term Empty).realize (Empty.elim : Empty → M))
        = Fin.elim0 from funext fun i => i.elim0]
      exact hφreal
    · exact absurd ((tailTemplateOfSeq_truth_sentence_iff a φ).mpr hφreal) hnot
  | k + 2, hk =>
    cases hk
    rcases hcase with ⟨_, rfl⟩ | ⟨hnot, _⟩
    · refine (realize_templateSentence_of_structure (L := L') (J := J) (N := M) φ t).mpr ?_
      rw [show (fun i : Fin 0 => (Term.func (Sum.inr (t i) : L'[[J]].Functions 0)
          Fin.elim0 : L'[[J]].Term Empty).realize (Empty.elim : Empty → M))
        = Fin.elim0 from funext fun i => i.elim0]
      exact hφreal
    · exact absurd ((tailTemplateOfSeq_truth_sentence_iff a φ).mpr hφreal) hnot

/-! ## Acceptance: tail-template realizability from the local EM model -/

/-- **Context-generic acceptance**: any local EM context over the seed stage with
`ΓEMlocal`-closure, support-covered Ω-completeness, and a template that agrees with the input's
on `Set.range s` realizes the input's tail-template theory. The common core of the subsequence
acceptance below (agreement from `tailTemplateOfSeq_comp_truth_iff`) and the
full-indiscernibility wiring (agreement from the absolute Morley-seed values,
`morleySeed_template_agreement` — no subsequence relation to the input needed). -/
theorem tailTemplateRealizable_of_localEMContext {L' : Language.{0, 0}}
    [Countable (Σ n, L'.Functions n)] [Countable (Σ n, L'.Relations n)]
    (s : ℕ → Σ n, L'.BoundedFormulaω Empty n) (M : Type) [L'.Structure M] [Nonempty M]
    (a : ℕ → M) (J : Type) [LinearOrder J] :
    letI : (localColim (LocalStage.ofSeq L' s)).Structure M :=
      localColimStructure (LocalStage.ofSeq L' s)
    ∀ (ctx : LocalEMContext (localColim (LocalStage.ofSeq L' s)) J (M := M)),
      ΓEMlocal (LocalStage.ofSeq L' s) ⊆ ctx.Γ →
      LocalEMContext.OmegaCompleteForColim (LocalStage.ofSeq L' s) J ctx →
      (∀ (n : ℕ) (ψ : L'.BoundedFormulaω Empty n), ⟨n, ψ⟩ ∈ Set.range s →
        ((tailTemplateOfSeq (L := L') ctx.a).truth ψ ↔
          (tailTemplateOfSeq (L := L') a).truth ψ)) →
      ∃ (N : Type) (_ : L'[[J]].Structure N),
        Theoryω.Model ((tailTemplateOfSeq (L := L') a).templateTheoryOfSeq s J) N := by
  let : (localColim (LocalStage.ofSeq L' s)).Structure M :=
    localColimStructure (LocalStage.ofSeq L' s)
  intro ctx hΓ hc hagree
  let : (localColim (LocalStage.ofSeq L' s))[[J]].Structure ctx.Carrier := ctx.structure
  let : L'[[J]].Structure ctx.Carrier :=
    ((LlocalInclusion (LocalStage.ofSeq L' s) 0).addConstants J).reduct ctx.Carrier
  have hmodel := LocalEMContext.templateTheoryOn_seed_model (LocalStage.ofSeq L' s) J ctx hΓ hc
  refine ⟨ctx.Carrier, inferInstance, ?_⟩
  rw [show ((tailTemplateOfSeq (L := L') a).templateTheoryOfSeq s J)
      = ((tailTemplateOfSeq (L := L') ctx.a).templateTheoryOn (Set.range s) J) from
    (Lomega1omegaTemplate.templateTheoryOn_congr hagree J).symm]
  exact hmodel

/-- **Cross-source acceptance**: the context-generic acceptance with the context's source carrier
separated from the input sequence's carrier — `ctx.a` lives in a mixin-satisfying `Source` (the
schema term model), while the input `a` lives in an arbitrary `L'`-structure `A` (the large
model). The template agreement hypothesis is the cross-model Morley-seed agreement's shape. The
source's seed semantics are read through the seed-language reduct; no `Nonempty Source` is
needed. -/
theorem tailTemplateRealizable_of_localEMContext_cross {L' : Language.{0, 0}}
    [Countable (Σ n, L'.Functions n)] [Countable (Σ n, L'.Relations n)]
    (s : ℕ → Σ n, L'.BoundedFormulaω Empty n)
    {A : Type} [L'.Structure A] (a : ℕ → A)
    (Source : Type) [(localColim (LocalStage.ofSeq L' s)).Structure Source]
    (hsk : LocalSkolemUniversalForColim (LocalStage.ofSeq L' s) (M := Source))
    (J : Type) [LinearOrder J] :
    letI : L'.Structure Source := (LlocalInclusion (LocalStage.ofSeq L' s) 0).reduct Source
    ∀ (ctx : LocalEMContext (localColim (LocalStage.ofSeq L' s)) J (M := Source)),
      ΓEMlocal (LocalStage.ofSeq L' s) ⊆ ctx.Γ →
      LocalEMContext.OmegaCompleteForColim (LocalStage.ofSeq L' s) J ctx →
      (∀ (n : ℕ) (ψ : L'.BoundedFormulaω Empty n), ⟨n, ψ⟩ ∈ Set.range s →
        ((tailTemplateOfSeq (L := L') ctx.a).truth ψ ↔
          (tailTemplateOfSeq (L := L') a).truth ψ)) →
      ∃ (N : Type) (_ : L'[[J]].Structure N),
        Theoryω.Model ((tailTemplateOfSeq (L := L') a).templateTheoryOfSeq s J) N := by
  let : L'.Structure Source := (LlocalInclusion (LocalStage.ofSeq L' s) 0).reduct Source
  intro ctx hΓ hc hagree
  let : (localColim (LocalStage.ofSeq L' s))[[J]].Structure ctx.Carrier := ctx.structure
  let : L'[[J]].Structure ctx.Carrier :=
    ((LlocalInclusion (LocalStage.ofSeq L' s) 0).addConstants J).reduct ctx.Carrier
  have hmodel := LocalEMContext.templateTheoryOn_seed_model_of_skolemUniversal
    (LocalStage.ofSeq L' s) J hsk ctx hΓ hc
  refine ⟨ctx.Carrier, inferInstance, ?_⟩
  rw [show ((tailTemplateOfSeq (L := L') a).templateTheoryOfSeq s J)
      = ((tailTemplateOfSeq (L := L') ctx.a).templateTheoryOn (Set.range s) J) from
    (Lomega1omegaTemplate.templateTheoryOn_congr hagree J).symm]
  exact hmodel

/-- **Per-`s` tail-template realizability via the local EM construction** (the acceptance
lemma): given the input sequence's tail indiscernibility on `Set.range s` and, **for that
`s`**, the hypothesis `hOmega` — an extracted subsequence context over
`localColim (LocalStage.ofSeq L' s)` that is `OmegaCompleteForColim` — the tail-template theory
of `a` over any target order `J` has a model.

This lemma is hypothesis-relative and true for every `s`; what is **not** claimed is that
`hOmega` is dischargeable for arbitrary `s` — its ∀-`s` closure is false-shaped (see the file
docstring; a `{Pᵢ} ∪ {⋀ᵢ Pᵢ}` seed against a height model defeats any extraction). The honest
instantiation is at `s := morleySeed φ` (`MorleySeedOmegaExtraction`). Every conjunct of
`hOmega` **except** `ctx.OmegaCompleteForColim` is proved by `exists_localEMContext_subseq`.
The extracted context's template agrees with the input's on the seed family
(`tailTemplateOfSeq_comp_truth_iff` — this is why `hOmega` demands `ctx.a = a ∘ g` for an order
embedding `g`, rather than an unrelated extracted sequence), so the model of the extracted
template theory is a model of `a`'s. -/
theorem tailTemplateRealizable_of_localEM {L' : Language.{0, 0}}
    [Countable (Σ n, L'.Functions n)] [Countable (Σ n, L'.Relations n)]
    (s : ℕ → Σ n, L'.BoundedFormulaω Empty n) (M : Type) [L'.Structure M] [Nonempty M]
    (a : ℕ → M) (J : Type) [LinearOrder J]
    (hTail : IsLomega1omegaIndiscernibleOnTail (L := L') a (Set.range s))
    (hOmega : letI : (localColim (LocalStage.ofSeq L' s)).Structure M :=
        localColimStructure (LocalStage.ofSeq L' s)
      ∃ (g : ℕ ↪o ℕ) (ctx : LocalEMContext (localColim (LocalStage.ofSeq L' s)) J (M := M)),
        ctx.a = a ∘ ⇑g ∧ ctx.Γ = ΓEMlocal (LocalStage.ofSeq L' s) ∧
        LocalEMContext.OmegaCompleteForColim (LocalStage.ofSeq L' s) J ctx) :
    ∃ (N : Type) (_ : L'[[J]].Structure N),
      Theoryω.Model
        ((tailTemplateOfSeq (L := L') a).templateTheoryOfSeq s J) N := by
  let : (localColim (LocalStage.ofSeq L' s)).Structure M :=
    localColimStructure (LocalStage.ofSeq L' s)
  obtain ⟨g, ctx, hctxa, hctxΓ, hc⟩ := hOmega
  refine tailTemplateRealizable_of_localEMContext s M a J ctx hctxΓ.symm.subset hc ?_
  intro n φ hφ
  rw [hctxa]
  exact hTail.tailTemplateOfSeq_comp_truth_iff g hφ

/-- **The seed Ω-residual, named**: for the Morley-seed setup — sentence `φ` holding in the
large source model `M`, input sequence `a` pairwise distinct and tail-indiscernible on
`Set.range (morleySeed φ)`, target order `J` — there is an extracted subsequence context
(`ctx.a = a ∘ g`, `ctx.Γ = ΓEMlocal`) that is `ΓlocalColim`-restricted `⋁`/`⋀`-complete.

Deliberately **seed-specific and source-aware**: the ∀-`s` closure of the acceptance bundle is
false-shaped (see `TailTemplateRealizable`'s docstring in `Conditional/MorleyHanfTransfer.lean` —
a seed enumerating `{Pᵢ x}ᵢ ∪ {⋀ᵢ Pᵢ x}` against a height model defeats any extraction), so the
residual carries exactly the facts the Morley–Hanf bridge actually has, including the `ℶ_{ω₁}`
premise, all available to the future combinatorial proof. Every conjunct except
`OmegaCompleteForColim` is already proved without them (`exists_localEMContext_subseq`). The
downstream Conditional-facing `morleySeedTailTemplateRealizable_of_localEMOmega` shows this
residual implies `MorleySeedTailTemplateRealizable` (modulo the extra function-symbol
countability of this bridge).

**WARNING — REFUTED** (`not_morleySeedOmegaExtraction_height`, `LocalEMOmegaResidual.lean`):
even seed-specific and source-aware, this bundle is false — the height pattern hides inside the
true seed sentence `∃x, ¬⋀ᵢ Pᵢ(x)`, whose subformula closure re-imports the divergent
conjunction into `ΓlocalColim`. Kept as the historical bundle shape; the honest residual must
sit below `OmegaCompleteForColim`. -/
def MorleySeedOmegaExtraction (L' : Language.{0, 0}) [Countable (Σ n, L'.Functions n)]
    [Countable (Σ n, L'.Relations n)] : Prop :=
  ∀ (φ : L'.Sentenceω) (M : Type) [L'.Structure M] [Nonempty M] (a : ℕ → M)
    (J : Type) [LinearOrder J],
    Cardinal.mk M ≥ Cardinal.beth (Ordinal.omega 1) →
    Sentenceω.Realize φ M →
    (∀ i j : ℕ, i ≠ j → a i ≠ a j) →
    IsLomega1omegaIndiscernibleOnTail (L := L') a (Set.range (morleySeed φ)) →
    letI : (localColim (LocalStage.ofSeq L' (morleySeed φ))).Structure M :=
      localColimStructure (LocalStage.ofSeq L' (morleySeed φ))
    ∃ (g : ℕ ↪o ℕ)
      (ctx : LocalEMContext (localColim (LocalStage.ofSeq L' (morleySeed φ))) J (M := M)),
      ctx.a = a ∘ ⇑g ∧ ctx.Γ = ΓEMlocal (LocalStage.ofSeq L' (morleySeed φ)) ∧
      LocalEMContext.OmegaCompleteForColim (LocalStage.ofSeq L' (morleySeed φ)) J ctx

/-- **The seed homogeneity residual** — the final frontier in its cleanest form: for the
Morley-seed setup there is a subsequence `a ∘ g` that is tail-indiscernible on `ΓEMlocal`
**and** source-side Ω-homogeneous (`LocalEMOmegaHomogeneous`). `J`-free — the target order
enters only downstream, through `omegaCompleteForColim_of_omegaHomogeneous`, for every `J` at
once. Seed-specific and source-aware like `MorleySeedOmegaExtraction` (whose docstring records
why the ∀-`s` form is false-shaped); the `ℶ_{ω₁}` and `φ`-realization facts are available to
the future combinatorial proof. The plain Ramsey extraction
(`exists_orderEmb_tailIndiscernible_ΓEMlocal`) already achieves the first conjunct; the
remaining content is the second — a countable-family homogeneity statement about eventual truth
of the de-substituted seed-family formulas on consecutive `(a ∘ g)`-tuples, with no term model,
no quotients, no supports.

**WARNING — REFUTED** (`not_morleySeedOmegaHomogeneousExtraction_height`,
`LocalEMOmegaResidual.lean`): the uniform `iInf`-cutoff clause fails for every subsequence of
the height sequence once the divergent conjunction hides inside a true seed sentence. Kept as
the historical clean form; see `LocalEMOmegaResidual.lean` for the audit and the reshape
direction. -/
def MorleySeedOmegaHomogeneousExtraction (L' : Language.{0, 0})
    [Countable (Σ n, L'.Functions n)] [Countable (Σ n, L'.Relations n)] : Prop :=
  ∀ (φ : L'.Sentenceω) (M : Type) [L'.Structure M] [Nonempty M] (a : ℕ → M),
    Cardinal.mk M ≥ Cardinal.beth (Ordinal.omega 1) →
    Sentenceω.Realize φ M →
    (∀ i j : ℕ, i ≠ j → a i ≠ a j) →
    IsLomega1omegaIndiscernibleOnTail (L := L') a (Set.range (morleySeed φ)) →
    letI : (localColim (LocalStage.ofSeq L' (morleySeed φ))).Structure M :=
      localColimStructure (LocalStage.ofSeq L' (morleySeed φ))
    ∃ g : ℕ ↪o ℕ,
      IsLomega1omegaIndiscernibleOnTail (a ∘ ⇑g)
        (ΓEMlocal (LocalStage.ofSeq L' (morleySeed φ))) ∧
      LocalEMOmegaHomogeneous (LocalStage.ofSeq L' (morleySeed φ)) (a ∘ ⇑g)

/-- **The seed homogeneity residual discharges the seed Ω-residual**: a homogeneous extraction
yields, for every target order `J`, the subsequence context bundle — the context is the
canonical one over `a ∘ g` (as in `exists_localEMContext_subseq`), and its
`OmegaCompleteForColim` comes from the reduction theorem
`omegaCompleteForColim_of_omegaHomogeneous`. -/
theorem morleySeedOmegaExtraction_of_homogeneousExtraction {L' : Language.{0, 0}}
    [Countable (Σ n, L'.Functions n)] [Countable (Σ n, L'.Relations n)]
    (h : MorleySeedOmegaHomogeneousExtraction L') : MorleySeedOmegaExtraction L' := by
  intro φ M instM instNe a J instJ hSize hφreal hPair hTail
  let : (localColim (LocalStage.ofSeq L' (morleySeed φ))).Structure M :=
    localColimStructure (LocalStage.ofSeq L' (morleySeed φ))
  obtain ⟨g, hind, hhom⟩ := h φ M a hSize hφreal hPair hTail
  refine ⟨g, ⟨a ∘ ⇑g, ΓEMlocal (LocalStage.ofSeq L' (morleySeed φ)), hind,
    locDeEqAtom_mem_ΓEMlocal J (LocalStage.ofSeq L' (morleySeed φ)),
    locDeRelAtom_mem_ΓEMlocal J (LocalStage.ofSeq L' (morleySeed φ))⟩, rfl, rfl, ?_⟩
  exact LocalEMContext.omegaCompleteForColim_of_omegaHomogeneous
    (LocalStage.ofSeq L' (morleySeed φ)) J _ hhom

end FirstOrder.Language
