/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
module

public import VaughtConjecture.AmalgamationPlan.ConvexGeometry

/-! # Plans are generated by sets of at most two points -/

@[expose] public section

namespace VaughtConjecture.AmalgamationPlan.Plan

variable {α : Type*} [DecidableEq α]

theorem extremes_hull_subset {A S : Finset α} {P : Finset (Finset α)}
    (hS : S ⊆ A) : extremes P (hull A P S) ⊆ S := by
  intro x hx
  obtain ⟨hxH, hxP⟩ := mem_extremes.mp hx
  by_contra hn
  have hsub : S ⊆ (hull A P S).erase x := by
    intro y hy
    exact Finset.mem_erase.mpr ⟨fun he => hn (he ▸ hy), subset_hull hS hy⟩
  exact Finset.notMem_erase x _ (hull_minimal hxP hsub hxH)

theorem extremes_singleton {P : Finset (Finset α)} (h0 : ∅ ∈ P) (a : α) :
    extremes P {a} = {a} := by
  ext x
  simp only [mem_extremes, Finset.mem_singleton]
  exact ⟨And.left, fun h => ⟨h, by simpa [h] using h0⟩⟩

theorem IsPlan.extremes_card_le_two {A B : Finset α} {P : Finset (Finset α)}
    (hP : IsPlan A P) (hB : B ∈ P) : (extremes P B).card ≤ 2 := by
  by_cases h : 2 ≤ B.card
  · exact (hP.extremes_card hB h).le
  · exact (Finset.card_le_card (Finset.filter_subset _ _)).trans (by omega)

/-- A visible face is exactly the hull of its removable points. -/
theorem IsPlan.hull_extremes {A B : Finset α} {P : Finset (Finset α)}
    (hP : IsPlan A P) (hB : B ∈ P) : hull A P (extremes P B) = B := by
  by_cases h0 : B = ∅
  · subst B
    simpa [extremes] using hP.hull_eq hP.empty_mem
  by_cases h1 : B.card = 1
  · obtain ⟨a, rfl⟩ := Finset.card_eq_one.mp h1
    rw [extremes_singleton hP.empty_mem]
    exact hP.hull_eq hB
  have h2 : 2 ≤ B.card := by
    have := Finset.card_pos.mpr (Finset.nonempty_iff_ne_empty.mpr h0)
    omega
  obtain ⟨a, b, ha, hb, _, hpiv, _, hgen⟩ := (restrict_isPlan hP hB).pivot_pair h2
  have hsub : hull A P (extremes P B) ⊆ B := hull_minimal hB (Finset.filter_subset _ _)
  apply hgen _ (Finset.mem_inter.mpr ⟨hP.hull_mem, Finset.mem_powerset.mpr hsub⟩)
  · apply subset_hull ((Finset.filter_subset _ _).trans (hP.subset_of_mem hB))
    exact mem_extremes.mpr ⟨ha, (Finset.mem_inter.mp ((hpiv a ha).mpr (Or.inl rfl))).1⟩
  · apply subset_hull ((Finset.filter_subset _ _).trans (hP.subset_of_mem hB))
    exact mem_extremes.mpr ⟨hb, (Finset.mem_inter.mp ((hpiv b hb).mpr (Or.inr rfl))).1⟩

/-- Every hull is generated by at most two of the original points. -/
theorem IsPlan.exists_small_generator {A S : Finset α} {P : Finset (Finset α)}
    (hP : IsPlan A P) (hS : S ⊆ A) :
    ∃ T ⊆ S, T.card ≤ 2 ∧ hull A P T = hull A P S :=
  ⟨extremes P (hull A P S), extremes_hull_subset hS,
    hP.extremes_card_le_two hP.hull_mem, hP.hull_extremes hP.hull_mem⟩

/-- No two different point-pairs (including the empty and singleton cases)
have the same hull. -/
theorem IsPlan.extremes_hull_small {A S : Finset α} {P : Finset (Finset α)}
    (hP : IsPlan A P) (hS : S ⊆ A) (hcard : S.card ≤ 2) :
    extremes P (hull A P S) = S := by
  by_cases h0 : S = ∅
  · subst S
    rw [hP.hull_eq hP.empty_mem]
    simp [extremes]
  by_cases h1 : S.card = 1
  · obtain ⟨a, rfl⟩ := Finset.card_eq_one.mp h1
    rw [hP.hull_eq (hP.singleton_mem (hS (Finset.mem_singleton_self _))),
      extremes_singleton hP.empty_mem]
  have h2 : S.card = 2 := by
    have := Finset.card_pos.mpr (Finset.nonempty_iff_ne_empty.mpr h0)
    omega
  apply Finset.eq_of_subset_of_card_le (extremes_hull_subset hS)
  rw [h2, hP.extremes_card hP.hull_mem]
  exact h2 ▸ Finset.card_le_card (subset_hull hS)

theorem IsPlan.hull_small_injective {A : Finset α} {P : Finset (Finset α)}
    (hP : IsPlan A P) {S T : Finset α} (hS : S ⊆ A) (hT : T ⊆ A)
    (hs : S.card ≤ 2) (ht : T.card ≤ 2) (h : hull A P S = hull A P T) : S = T := by
  rw [← hP.extremes_hull_small hS hs, h, hP.extremes_hull_small hT ht]

/-- Closed faces and sets of at most two ground points are in bijection. -/
def IsPlan.faceEquivSmall {A : Finset α} {P : Finset (Finset α)} (hP : IsPlan A P) :
    {B // B ∈ P} ≃ {S : Finset α // S ⊆ A ∧ S.card ≤ 2} where
  toFun B := ⟨extremes P B, (Finset.filter_subset _ _).trans (hP.subset_of_mem B.2),
    hP.extremes_card_le_two B.2⟩
  invFun S := ⟨hull A P S, hP.hull_mem⟩
  left_inv B := Subtype.ext (hP.hull_extremes B.2)
  right_inv S := Subtype.ext (hP.extremes_hull_small S.2.1 S.2.2)

theorem IsPlan.card_eq_small {A : Finset α} {P : Finset (Finset α)} (hP : IsPlan A P) :
    P.card = (A.powerset.filter fun S => S.card ≤ 2).card := by
  apply Finset.card_bij (fun B _ => extremes P B)
  · intro B hB
    exact Finset.mem_filter.mpr ⟨Finset.mem_powerset.mpr
      ((Finset.filter_subset _ _).trans (hP.subset_of_mem hB)), hP.extremes_card_le_two hB⟩
  · intro B hB C hC he
    rw [← hP.hull_extremes hB, he, hP.hull_extremes hC]
  · intro S hS
    obtain ⟨hm, hc⟩ := Finset.mem_filter.mp hS
    exact ⟨hull A P S, hP.hull_mem, hP.extremes_hull_small (Finset.mem_powerset.mp hm) hc⟩

/-- The number of visible faces depends only on the ground-set cardinality. -/
theorem IsPlan.card {A : Finset α} {P : Finset (Finset α)} (hP : IsPlan A P) :
    P.card = 1 + A.card + A.card.choose 2 := by
  rw [hP.card_eq_small]
  have he : A.powerset.filter (fun S => S.card ≤ 2) =
      A.powersetCard 0 ∪ A.powersetCard 1 ∪ A.powersetCard 2 := by
    ext S
    simp only [Finset.mem_filter, Finset.mem_powerset, Finset.mem_union,
      Finset.mem_powersetCard]
    by_cases hs : S ⊆ A <;> simp only [hs, true_and, false_and, or_self]
    omega
  have hd {i j : ℕ} (hne : i ≠ j) : Disjoint (A.powersetCard i) (A.powersetCard j) := by
    apply Finset.disjoint_left.mpr
    intro S hi hj
    exact hne ((Finset.mem_powersetCard.mp hi).2.symm.trans (Finset.mem_powersetCard.mp hj).2)
  rw [he, Finset.card_union_of_disjoint
      (Finset.disjoint_union_left.mpr ⟨hd (by omega), hd (by omega)⟩),
    Finset.card_union_of_disjoint (hd (by omega))]
  simp [Finset.card_powersetCard]

theorem IsPlan.card_nonempty {A : Finset α} {P : Finset (Finset α)} (hP : IsPlan A P) :
    (P.erase ∅).card = A.card + A.card.choose 2 := by
  rw [Finset.card_erase_of_mem hP.empty_mem, hP.card]
  omega

end VaughtConjecture.AmalgamationPlan.Plan
