/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
module

public import InfinitaryLogic.Descriptive.StructureSpace
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic

/-!
# Measurable Structure on the Structure Space

This file equips `StructureSpace L` with a `MeasurableSpace` structure, derived from
the product measurable space on `RelQuery L → Bool`. The key result is that cylinder
sets (sets determined by a single relation query) are measurable.

## Main Results

- `StructureSpace.instMeasurableSpace`: `MeasurableSpace` instance on `StructureSpace L`.
- `measurableSet_relHolds`: The set of codes where a given relation query holds is measurable.
-/

@[expose] public section

universe u v

namespace FirstOrder

namespace Language

open MeasureTheory

-- Generic instance: StructureSpaceOn is abbrev, so TC sees through it automatically.
instance {α : Type*} : MeasurableSpace (StructureSpaceOn L α) := MeasurableSpace.pi

/-- The set of codes where a given relation query returns `true` is measurable (generic). -/
theorem measurableSet_relHoldsOn {α : Type*} (q : RelQueryOn L α) :
    MeasurableSet {c : StructureSpaceOn L α | c q = true} := by
  have : {c : StructureSpaceOn L α | c q = true} = (fun c => c q) ⁻¹' {true} := by
    ext c; simp
  rw [this]
  exact (measurable_pi_apply q) (measurableSet_singleton true)

/-- `StructureSpace L` inherits the product measurable space from `RelQuery L → Bool`.
Since `Bool` has `MeasurableSpace Bool := ⊤` (all sets measurable), this is the
σ-algebra generated by cylinder sets. -/
instance : MeasurableSpace (StructureSpace L) :=
  MeasurableSpace.pi

/-- The set of codes where a given relation query returns `true` is measurable.
These are the basic cylinder sets generating the σ-algebra. -/
theorem measurableSet_relHolds (q : RelQuery L) :
    MeasurableSet {c : StructureSpace L | c q = true} := by
  have : {c : StructureSpace L | c q = true} = (fun c => c q) ⁻¹' {true} := by
    ext c; simp
  rw [this]
  exact (measurable_pi_apply q) (measurableSet_singleton true)

end Language

end FirstOrder
